name: polling_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  firebase_core: ^3.2.0
  cloud_firestore: 5.1.0
  firebase_auth: 5.1.2
  salomon_bottom_bar: 3.3.2
  get_storage: 2.1.1
  image_picker: 1.1.2
  firebase_storage: 12.1.1
  firebase_app_check: 0.3.0+3
  intl: 0.19.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

